### ISSUE TITLE
Updating Red Eclipse at Ubuntu Repository

### ISSUE THREAD

**Issue by YourTeddyBear** [red-eclipse/world#19]
Dear Red Eclipse PPL,

i've installed Red Eclipse using the apt-get mechanism of Ubuntu. After doing this I noticed that its an old version 1.5.1 of the game. On your site there is a new version called 1.6.0. It would be cool if you could update the packet, so the correct version could be installed using apt.

I really like to thank you for this.

Greetings

Your TeddyBear

**Comment by qreeves** [comment]
Sorry, but we don't officially support the package managers of operating systems because they are not something we have any control over. This is an ongoing issue, and due to the fact these repositories fail to get updated so often we ask that everyone download the game from our official packages at: http://redeclipse.net/download

**Comment by acerspyro** [comment]
@voidanix Please do not suggest using Red Eclipse from a repository as we do not support them and have zero control over them.

So far, they have created more trouble than they are worth, so please steer away from the repo releases and grab the official version of Red Eclipse at http://redeclipse.net/download.

**Comment by YourTeddyBear** [comment]
Thank you for your answers, finally I downloaded it from the original site. Really thank you for help!
