### ISSUE TITLE
Will the extremely lightweight version be kept supported?

### ISSUE THREAD

**Issue by Tachobrenner** [red-eclipse/world#44]
I've read that the Game will be based on Tesseract, which is heavier. Will the old version lose the support? It matters if you play on a really old machine.

**Comment by JeffBobbo** [comment]
Short answer is yes.

While the tesseract version is a long ways off still, the differences between the two aren't compatible. Maps have been changed for the new engine and gameplay changes have occurred that make the two sufficiently different. Upon release some 1.6 servers may still be on the master server, so you'll still be able to play, but I doubt you'll get any support in terms of new developments or bug fixes.

Of course, you (and any one else) is free to run their own master server for 1.6.

**Comment by qreeves** [comment]
I will probably retain support for v1.6 in some form or another for a fair time during the transition period, probably as another branch so any *serious* bugs can still be patched. There's nothing wrong with it, so I see no reason to prevent the community from playing it, but I will only be promoting v2.0 once it is released.

As @JeffBobbo mentioned, the development version has branched off significantly from its predecessor because I am using the relaunch as an opportunity to refine the gameplay and resolve some issues I've had with the way the gameplay evolved over the years.

Probably the biggest of these changes is the way weapon balancing is handled. In the past, we've mostly just had maximum ammo, delays, damage, speed, and range. This has sort-of resulted in a set of weapons that are fairly similar and somewhat bland. I've been working on a system that introduces more varied balancing mechanisms such as limited ammo, player weight, speed, etc; thus making choosing weapons more like picking a character class in something like TF2, except you're building your own character based on what you pick.

**Comment by qreeves** [comment]
Closing due to being marked as solved. If you still require help please feel free to open a new request.
