### ISSUE TITLE
Should the length of a match be changed?

### ISSUE THREAD

**Issue by qreeves** [red-eclipse/world#7]
Long ago I settled on making the time limit for everything 10 minutes. After some thought on the issue recently I wondered if increasing or decreasing the time limits would have some sort of impact on player retention. I'd like to trial some changes to see how it changes average session lengths, so welcome to the first poll in our new discussion area!

### Poll Results
![image](https://user-images.githubusercontent.com/3297929/34992339-9eb676d2-fb18-11e7-82fd-e7f0d20d8105.png)
**Winner:** Leave everything at 10 minutes.

**Comment by Dziq84** [comment]
I vote for 12 minutes ;p

**Comment by ZeroKnight** [comment]
As a quick note, you mention that you'd like to experiment with "increasing **or decreasing** the time limits", but there is no poll option for less than 10m, the current default.

I suppose the answer in general would really depend on how you and the community as a whole expect and/or want the game to be paced. Shorter time limits allow for more matches in the same amount of time, which would let players—new ones especially—experience a wider array of game modes and mutators than they would otherwise with the current default time limit for the same investment of their time. On the other hand, a game that runs on the "long" side gives you plenty of time to really get into a good match and enjoy it for a decent amount of time before moving onto the next; shorter games might feel like they have less substance by comparison.

In my opinion, I think that in general, people tend to prefer games that they can easily hop into and play a handful of matches within a reasonably short amount of time, while sticking around for extended durations if they so choose; this is a bit harder to do with games that require a larger time investment, as it feels like a bigger 'commitment' of sorts.

**Comment by acerspyro** [comment]
I think 30 seconds should be reasonable for any match.

**Comment by IceflowRE** [comment]
You can vote multiple times?

**Comment by SniperGoth** [comment]
5 minutes would be too short, and depending on the gamemode (race mostly on a non-infinite time server), is too short to be honest.
15 minutes onward is too long.
I still find 10 minutes to be perfect for any gamemode.

**Comment by qreeves** [comment]
**Winner:** Leave everything at 10 minutes.

Thanks to everyone who voted! 😃
